Added add_image_provider method to qml engine
woboq/qmetaobject-rs pull request #132
Opened 2021-04-19 00:20 UTC by zethra

There currently isn't a way to construct a QQuickImageProvider in Rust but without this method there is no way to use one at all, even defined in cpp.

I've added this because I need for a project. I'd be nice to add a way to construct a QQuickImageProvider in Rust but that's beyond me.

2021-04-19 04:00 UTC, ogoffart requested changes
Thanks for your contribution!

Howerver i'm afraid this can't be done like that.

The function takes a raw pointer. As such, it should be marked as `unsafe` because it would cause a crash to pass a dangling pointer.

But this show that we don't really want this as is, because, as you said, it would be better to have a pure rust way to add the  QQuickImageProvider.
That would be a bigger work and i understand that you are not ready to contribute that.

What I suggest instead would be to expose a function such as `fn cpp_ptr(&self) -> *mut c_void` to QQmlEngine that return a pointer to the C++ `QQmlEngine`  so you can call the `addImageProvider` function yourself in the code base which also creates the image provider itself.
I believe this would solve your problem, and would also allow many more extensions for other use cases which are currently not exposed by this crate.

2021-04-19 08:27 UTC, ratijas commented
Image providers and icons are such a messed up pain in Qt/QML, I could still feel that from a year ago, haha

I think, I did something similar to what @ogoffart described, but for wrapping a different package: get a raw pointer to the engine, and do whatever with it. This [QuickFlux wrapper](https://github.com/InnopolisUniversity/innometrics-agent-os-linux/commit/4b7221fa8f778ea57320a4527c251db148f0cd78) is just an example idea of what you could do.

2021-04-19 09:47 UTC, ogoffart commented
@ratijas   ouch, i see in your QuickFlux wrapper that you copied the QmlEngineHolder into your own C++ file. But that sounds like a horrible hack :-/   I believe providing a (rust) `QmlEngine::cpp_ptr`  that returns a pointer should be indeed more appropriate for your use case as well.

2021-04-20 09:18 UTC, ogoffart commented
Commit 5d6b0ff added a function to get the raw pointer to QQmlEngine so you can use it in your application.

I'm closing this issue because this should allow you to do what you want.

If you really want to add a image provider api to this crate, it should be a purely rust one.

But thanks anyway for the contribution.

2021-04-20 09:18 UTC, closed without merging

2021-04-20 14:06 UTC, ratijas commented
> @ratijas ouch, i see in your QuickFlux wrapper that you copied the QmlEngineHolder into your own C++ file. But that sounds like a horrible hack :-/ 

Oh yeah, that repo is one huge pile of terrifying hacks. Luckily though, that was just a university project, and never made it into production. But, I mean… just imagine all the fun I have had coping with all that stuff.

I don't advice following my path, like in "don't try that at home". But just to get an idea of what's generally possible, it is good enough.

Pure rust handwritten wrappers are the way to go, provided that we have necessary foundation to build upon.

2021-09-12 16:30 UTC, timsueberkrueb commented
Hey there, I created an image provider API for my side project: [source code](https://github.com/timsueberkrueb/webber/blob/master/src/qt/image_provider.rs). Does that look like something that could be upstreamed? Thanks!