Refactored out QColor into its own module and increased Qcolor API coverage
woboq/qmetaobject-rs pull request #213
Opened 2021-11-16 10:10 UTC by ericcao119

This version does not break the current API. My only reservation is about how to handle default arguments going forward. This class has a lot of redundant methods like rgb_f, rgba_f, cymk_f, cymka_f that exist because of rust's lack of default arguments. Is the preference to use an Option or to just create multiple methods in the future.

2021-11-16 18:26 UTC, ogoffart commented
Looks good.
Can you rebase?

2021-11-16 18:30 UTC, ogoffart commented on qttypes/src/gui/qcolor.rs
> +    pub fn name_format(&self, format: NameFormat) -> QString {
maybe this should be renamed `name_with_format`  or just have `name` that always take a format.
another option would be to just have a `name_argb` and `name_rgb`.

2021-11-18 08:41 UTC, ogoffart requested changes
I still have a concern about the naming of Spec and NameFormat since they are re-exported at the top level, and their raw name is lacking context.


Regarding name, i'm a bit unsure if this is good api, but since that's also what Qt has, let's just go with that. (In my mind, this crate shouldn't be a 1:1 binding of Qt, but offer idiomatic rust API for using QML. So one does not have to just blindly take Qt API, but think about the best and more efficient naming.  But in that case i think it's ok to just follow Qt)

2021-11-18 08:41 UTC, ogoffart commented on qttypes/src/gui/qcolor.rs
> +pub enum Spec {
This should be named QColorSpec,  and NameFormat  QColorNameFormat, because it otherwise is not descriptive enough as it is outside of a namespace.

2021-11-18 08:41 UTC, ogoffart commented on qttypes/src/gui/qcolor.rs
> +    // #RRGGBB A "#" character followed by three two-digit hexadecimal numbers (i.e. #RRGGBB).
should be doc comment. (`///`)

2021-11-19 09:30 UTC, ericcao119 commented
I'm fine with the name change but I do think that name_with_format and name should be kept as separate functions since name_with_format allows you to specify the output format.

By idiomatic, do you mean using rust types for the most part? Like returning String rather than QString. Because otherwise I think the API is pretty straightforward.

2021-11-19 09:34 UTC, ericcao119 commented
Also, NameFormat and Spec don't need to be re-exported at the top level if that is what you prefer.

2021-11-19 09:57 UTC, ogoffart commented
> By idiomatic, do you mean using rust types for the most part? Like returning String rather than QString. Because otherwise I think the API is pretty straightforward.

I mean it is a tradeof between
 1. performance
 2. idiomatic
 3. mapping of the Qt API

And I try to keep that order.  So we use QString instead of String to avoid needless conversions. But for naming and what we expose, we prefer rust naming and convention to Qt/C++ ones.

2021-11-19 10:34 UTC, ogoffart commented
I pushed by mistake your commits into the master branch in e188dea9486c756970ef91d328eefd5b8f153f0b
as i had them locally to do some tests.  
So i'll close this PR (since it is merged, in fact) I'll do the last adjustments myself.

Thanks for the contribution.

2021-11-19 10:34 UTC, closed without merging